// tool/generate_keys_from_translations_dart.dart
// Generates lib/prefs/keys.dart from lib/prefs/translations.dart (GetX single-file map).
// Usage: dart run tool/generate_keys_from_translations_dart.dart

import 'dart:convert';
import 'dart:io';

void main(List<String> args) {
  const srcPath =
      'C:\\flutter_dev\\projects\\hello_mesa\\lib\\prefs\\translations.dart';
  const outPath =
      'C:\\flutter_dev\\projects\\hello_mesa\\lib\\prefs\\keys.dart';

  final src = File(srcPath);
  if (!src.existsSync()) {
    stderr.writeln('❌ Source file not found: $srcPath');
    exit(1);
  }

  final content = src.readAsStringSync();

  // Find the start of `get keys => {`
  final startPattern = RegExp(r'get\s+keys\s*=>\s*\{', multiLine: true);
  final startMatch = startPattern.firstMatch(content);
  if (startMatch == null) {
    stderr.writeln('❌ Could not find `get keys => {` in $srcPath');
    exit(1);
  }

  // Extract map literal by counting braces
  final startIndex = startMatch.end - 1;
  int braceCount = 0;
  int endIndex = -1;
  for (int i = startIndex; i < content.length; i++) {
    final ch = content[i];
    if (ch == '{') braceCount++;
    if (ch == '}') {
      braceCount--;
      if (braceCount == 0) {
        endIndex = i;
        break;
      }
    }
  }

  if (endIndex == -1) {
    stderr.writeln('❌ Could not find closing brace for map.');
    exit(1);
  }

  var mapLiteral = content.substring(startIndex, endIndex + 1);

  // Remove comments
  mapLiteral = mapLiteral.replaceAll(RegExp(r'//.*?$', multiLine: true), '');
  mapLiteral = mapLiteral.replaceAll(RegExp(r'/\*[\s\S]*?\*/'), '');

  // 🩹 Convert Dart-like single or double quoted strings into JSON-safe double quotes
  // and safely handle escaped single quotes like Today\'s → Today's.
  mapLiteral = mapLiteral.replaceAllMapped(
    RegExp(r"'([^'\\]*(?:\\.[^'\\]*)*)'"),
    (m) {
      var inner = m[1]!;
      // Unescape Dart-style \' → '
      inner = inner.replaceAll(r"\'", "'");
      // Escape any JSON double quotes inside
      inner = inner.replaceAll('"', r'\"');
      return '"$inner"';
    },
  );

// Remove trailing commas before closing braces/brackets to make valid JSON
  mapLiteral = mapLiteral.replaceAllMapped(
    RegExp(r',\s*(\}|\])'),
    (match) => match[1]!, // replace with the captured group (} or ])
  );

  // Try to parse JSON
  Map<String, dynamic> parsed;
  try {
    parsed = jsonDecode(mapLiteral) as Map<String, dynamic>;
  } catch (e) {
    stderr.writeln('❌ JSON parsing failed: $e');
    stderr.writeln('--- snippet ---');
    stderr.writeln(mapLiteral.substring(
        0, mapLiteral.length > 1000 ? 1000 : mapLiteral.length));
    stderr.writeln('--- end ---');
    exit(1);
  }

  // Merge all locales
  final merged = <String, dynamic>{};
  parsed.forEach((locale, value) {
    if (value is Map<String, dynamic>) {
      mergeRecursive(merged, value);
    }
  });

  // Generate Dart output
  final buffer = StringBuffer();
  buffer.writeln('// GENERATED CODE — DO NOT EDIT BY HAND');
  buffer.writeln(
      '// Generated by tool/generate_keys_from_translations_dart.dart\n');
  buffer.writeln('class TKeys {');
  for (final top in merged.keys) {
    final safe = _safeIdentifier(top);
    buffer.writeln('  static const $safe = _${_capitalize(safe)}();');
  }
  buffer.writeln('}\n');

  void generateNested(
      String className, Map<String, dynamic> node, String prefix) {
    buffer.writeln('class _$className {');
    buffer.writeln('  const _$className();');
    node.forEach((k, v) {
      final field = _safeIdentifier(k);
      final full = prefix.isEmpty ? k : '$prefix.$k';
      if (v is Map<String, dynamic>) {
        buffer.writeln('  final $field = _${_capitalize(field)}();');
      } else {
        buffer.writeln("  final String $field = '$full';");
      }
    });
    buffer.writeln('}\n');
    node.forEach((k, v) {
      if (v is Map<String, dynamic>) {
        generateNested(_capitalize(_safeIdentifier(k)), v,
            prefix.isEmpty ? k : '$prefix.$k');
      }
    });
  }

  merged.forEach((k, v) {
    if (v is Map<String, dynamic>) {
      generateNested(_capitalize(_safeIdentifier(k)), v, k);
    }
  });

  File(outPath)
    ..createSync(recursive: true)
    ..writeAsStringSync(buffer.toString());

  stdout.writeln('✅ Generated $outPath with ${merged.length} top-level keys.');
}

/// Merges map2 into map1
void mergeRecursive(Map<String, dynamic> map1, Map<String, dynamic> map2) {
  map2.forEach((k, v) {
    if (v is Map<String, dynamic>) {
      map1[k] ??= <String, dynamic>{};
      mergeRecursive(map1[k] as Map<String, dynamic>, v);
    } else {
      map1[k] = v;
    }
  });
}

String _safeIdentifier(String s) {
  final cleaned = s.replaceAll(RegExp(r'[^a-zA-Z0-9_]'), '_');
  if (RegExp(r'^[0-9]').hasMatch(cleaned)) return '_$cleaned';
  return cleaned;
}

String _capitalize(String s) =>
    s.isEmpty ? s : s[0].toUpperCase() + s.substring(1);
